In [1]:
import numpy as np
name=np.array(["王静雯","蔺婧","靳文龙","白卓岩","许言"])
subject=np.array(["Math","English","Python","Chinese","Art","Database","Physics"])
scores=np.array([[70,85,77,90,82,84,89],[60,64,80,75,80,92,90],[90,93,77,76,92,85,62],[88,55,60,95,71,56,59],[77,48,59,86,99,48,58]])
scores+5

array([[ 75,  90,  82,  95,  87,  89,  94],
       [ 65,  69,  85,  80,  85,  97,  95],
       [ 95,  98,  82,  81,  97,  90,  67],
       [ 93,  60,  65, 100,  76,  61,  64],
       [ 82,  53,  64,  91, 104,  53,  63]])

In [2]:
a=np.ones((5,7))*5
a+scores
scores

array([[70, 85, 77, 90, 82, 84, 89],
       [60, 64, 80, 75, 80, 92, 90],
       [90, 93, 77, 76, 92, 85, 62],
       [88, 55, 60, 95, 71, 56, 59],
       [77, 48, 59, 86, 99, 48, 58]])

In [3]:
bonus=np.array([3,4,5,3,6,7,2])
scores+bonus

array([[ 73,  89,  82,  93,  88,  91,  91],
       [ 63,  68,  85,  78,  86,  99,  92],
       [ 93,  97,  82,  79,  98,  92,  64],
       [ 91,  59,  65,  98,  77,  63,  61],
       [ 80,  52,  64,  89, 105,  55,  60]])

In [6]:
scores[name=="王静雯",subject=="Art"]+20

array([102])

In [11]:
np.floor(scores/10)

NameError: name 'floor' is not defined

In [9]:
np.subtract(scores,3)

array([[67, 82, 74, 87, 79, 81, 86],
       [57, 61, 77, 72, 77, 89, 87],
       [87, 90, 74, 73, 89, 82, 59],
       [85, 52, 57, 92, 68, 53, 56],
       [74, 45, 56, 83, 96, 45, 55]])

In [10]:
scores.sum(axis=0)

array([385, 345, 353, 422, 424, 365, 358])

In [14]:
scores[name=="靳文龙"].mean()

82.142857142857139

In [15]:
name[scores[:,subject=="English"].argmax()]

'靳文龙'

In [16]:
np.random.randint(0,6,10)

array([5, 3, 3, 0, 1, 4, 4, 2, 5, 2])

In [17]:
np.random.randint(0,2,size=(5,6))

array([[0, 0, 1, 0, 1, 1],
       [1, 1, 1, 0, 1, 0],
       [0, 0, 0, 1, 1, 1],
       [1, 1, 0, 0, 1, 0],
       [1, 1, 1, 0, 1, 1]])

In [18]:
np.random.normal(0,1,size=(4,5))

array([[ 0.90580287,  0.85345758, -1.74898921,  0.15406218,  0.84506595],
       [-0.19308811,  0.61886344,  1.16534904, -0.90806369,  0.70962148],
       [-0.48788404,  1.72092231,  1.46783685, -0.29494115, -0.06802308],
       [ 1.43589849,  0.99739087, -1.24939342, -0.75530442,  0.6244227 ]])

In [2]:
import numpy as np
name=np.array(["王静雯","蔺婧","靳文龙","白卓岩","许言"])
subject=np.array(["Math","English","Python","Chinese","Art","Database","Physics"])
scores=np.array([[70,85,77,90,82,84,89],[60,64,80,75,80,92,90],[90,93,77,76,92,85,62],[88,55,60,95,71,56,59],[77,48,59,86,99,48,58]])
scores.max()

99

In [5]:
np.random.choice(name)

'许言'

In [7]:
scores[:,subject=="English"]-5

array([[80],
       [59],
       [88],
       [50],
       [43]])