In [6]:
import numpy as np
random=np.random.normal(0,1,size=(3,10))
random
rndx=position[0]
rndy=position[1]
rndz=position[2]
[rndx,rndy,rndz]

[array([-0.52082677,  0.94896061,  0.76792678,  1.36660787,  1.18631937,
        -0.34294002,  0.24858224,  0.50180101, -0.9998671 , -1.64990069]),
 array([ 1.55563998,  1.17889614, -0.90073634, -0.43920821,  1.04463858,
         1.19419497,  1.63259945,  3.56930155,  3.30907844,  2.78319468]),
 array([ 0.82029991,  1.31737541,  1.62305969,  2.77963812,  3.62569652,
         2.46866438,  1.27123311,  0.77236724, -0.33557378,  0.29009545])]

In [7]:
position=random.cumsum(axis=1)
position

array([[ 1.53919932,  1.56811541,  1.54623036,  2.79042119,  2.2499801 ,
         1.59704179,  2.19823048,  2.33031551,  3.34756183,  2.09622216],
       [-0.56055469, -1.56141792, -0.28070679, -1.22190653, -2.3129754 ,
        -4.26932816, -4.17050599, -2.44802437, -2.97490283, -2.12592238],
       [ 1.37667267,  2.41511822,  2.37287378,  2.61720036,  2.54059292,
         2.6503448 ,  1.69907027,  1.66931504,  3.69644494,  5.14865054]])

In [17]:
dist=np.sqrt(position[0]**2+position[1]**2+position[2]**2)
np.set_printoptions(precision=2)
dist

array([ 2.14,  3.28,  2.85,  4.02,  4.11,  5.27,  5.01,  3.77,  5.81,  5.95])

In [25]:
abs(position[2]).max()

5.1486505423111391

In [22]:
dist.min()

2.1397625441357859