In [1]:
import numpy as np
market=np.array(["大润发","沃尔玛","联华","农工商"])
fruit=np.array(["苹果","香蕉","桔子","芒果"])
"""price=np.random.randint(4,11,size=(4,4))"""
price=np.random.randint(4,11,16).reshape(4,4)
price

array([[ 9,  7,  5,  9],
       [ 5,  6,  7,  7],
       [ 6,  8,  8,  4],
       [ 5,  5, 10,  9]])

In [3]:
price[[0,2],[0,1]]+1

array([10,  9])

In [38]:
price[market=="联华",fruit=="香蕉"]+1

array([6])

price[(market=="农工商")]-2

In [9]:
price[fruit=="苹果"].mean()

7.5

In [10]:
price[fruit=="芒果"].mean()

7.25

In [19]:
market[price[fruit=="桔子"].argmax()]

'沃尔玛'