In [5]:
import numpy as np
import pandas as pd
from pandas import DataFrame,Series

#1)    从文件中读出所需的数据，根据分析需求将所需的数据保存到DataFrame中（3分）

data=pd.read_csv("F:\Python\data\Animals.csv")
print(data[0:5])

   Unnamed: 0      name  hair  feathers  eggs  milk  airborne  aquatic  \
0           0  aardvark     1         0     0     1         0        0   
1           1  antelope     1         0     0     1         0        0   
2           2      bass     0         0     1     0         0        1   
3           3      bear     1         0     0     1         0        0   
4           4      boar     1         0     0     1         0        0   

   predator  toothed  backbone  breathes  venomous  fins  legs  tail     type  
0         1        1         1         1         0     0     4     0  Mammals  
1         0        1         1         1         0     0     4     1  Mammals  
2         1        1         1         0         0     1     0     1   Others  
3         1        1         1         1         0     0     4     0  Mammals  
4         1        1         1         1         0     0     4     1  Mammals  


In [12]:
#2)    判断数据集中是否有缺失数据，并采取合适的方法处理（3分）

isnull=data.isnull().any()
print(isnull)
#不存在缺失数据

Unnamed: 0    False
name          False
hair          False
feathers      False
eggs          False
milk          False
airborne      False
aquatic       False
predator      False
toothed       False
backbone      False
breathes      False
venomous      False
fins          False
legs          False
tail          False
type          False
dtype: bool


In [59]:
#3)    统计各类动物的数量，并列出每类动物的名字（3分）
data1=data.drop(["hair","feathers","eggs","milk","airborne","aquatic","predator","toothed","backbone","venomous","legs","fins","tail"])
typeNum=data1.drop(axis=1).groupby("type")
typeNum=print(typeNum)
print(data1["name"])

In [40]:
#4)    数据预处理，将'type'的值转换为数值类型（3分）

data.loc[data["type"]=="Mammals","type"]=0
data.loc[data["type"]=="Birds","type"]=1
data.loc[data["type"]=="Others","type"]=2

In [41]:
#5)    计算动物类型与蛋、尾巴特征之间的相关系数（3分）

print(data["type"].corr(data["eggs"]))

In [51]:
#6)    选择合适的数据列作为特征和标签形成数据集，并将数据集分为训练集和测试集（6分）

X = data.iloc[ :, 2:16].values.astype(float)
y = data.iloc[ :, 16].values.astype(int)
from sklearn import model_selection
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.35, random_state=1)

In [49]:
#7)    在训练集上建立决策树分类模型进行分类，并在测试集上做性能评估（需要计算准确率、打印分类报告和混淆矩阵）（6分）
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf.fit(X,y)  
predicted_y=clf.predict(X)
print(clf.score(X_test,y_test))
from sklearn import metrics
print(metrics.classification_report(y, predicted_y))
print(metrics.confusion_matrix(y, predicted_y))


1.0
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        41
          1       1.00      1.00      1.00        20
          2       1.00      1.00      1.00        40

avg / total       1.00      1.00      1.00       101

[[41  0  0]
 [ 0 20  0]
 [ 0  0 40]]


In [ ]:
#8)    根据第7）步的运行结果，说明算法在动物分类上的性能，用文字描述在程序的注释中（3分）
#通过第七步运行可知：算法准确率为1，说明准确率很高；分类报告显示precision、recall、fl-score值均为1，说明分类效果较好，混淆矩阵显示对角线以外矩阵元素为0，说明分类效果很好，总体来讲达到期望的分类效果