In [1]:
import numpy as np
name=np.array(["王静雯","蔺婧","靳文龙","白卓岩","许言"])
subject=np.array(["Math","English","Python","Chinese","Art","Database","Physics"])
scores=np.array([[70,85,77,90,82,84,89],[60,64,80,75,80,92,90],[90,93,77,76,92,85,62],[88,55,60,95,71,56,59],[77,48,59,86,99,48,58]])

In [3]:
subject[[0,1,3]]

array(['Math', 'English', 'Chinese'], 
      dtype='<U8')

In [4]:
name[-4]

'蔺婧'

In [8]:
name[1:5:1]

array(['蔺婧', '靳文龙', '白卓岩'], 
      dtype='<U3')

In [10]:
subject[1:4:1]

array(['English', 'Python', 'Chinese'], 
      dtype='<U8')

In [11]:
subject[(subject=="English")|(subject=="Physics")]

array(['English', 'Physics'], 
      dtype='<U8')

In [12]:
scores[[1,4]]

array([[60, 64, 80, 75, 80, 92, 90],
       [77, 48, 59, 86, 99, 48, 58]])

In [15]:
scores[[2,4]][:,(subject=="Math")|(subject=="Python")]

array([[90, 77],
       [77, 59]])

In [16]:
scores[:,(subject=="Math")|(subject=="Art")]

array([[70, 82],
       [60, 80],
       [90, 92],
       [88, 71],
       [77, 99]])

In [17]:
scores[[(name=="许言")|(name=="白卓岩")]]

array([[88, 55, 60, 95, 71, 56, 59],
       [77, 48, 59, 86, 99, 48, 58]])

In [20]:
np.arange(10,20,1).reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])