In [1]:
import numpy as np
name=np.array(["王静雯","蔺婧","靳文龙","白卓岩","许言"])
subject=np.array(["Math","English","Python","Chinese","Art","Database","Physics"])
scores=np.array([[70,85,77,90,82,84,89],[60,64,80,75,80,92,90],[90,93,77,76,92,85,62],[88,55,60,95,71,56,59],[77,48,59,86,99,48,58]])

In [2]:
scores-3

array([[67, 82, 74, 87, 79, 81, 86],
       [57, 61, 77, 72, 77, 89, 87],
       [87, 90, 74, 73, 89, 82, 59],
       [85, 52, 57, 92, 68, 53, 56],
       [74, 45, 56, 83, 96, 45, 55]])

In [4]:
scores.mean(axis=1)

array([ 82.42857143,  77.28571429,  82.14285714,  69.14285714,  67.85714286])

In [13]:
ary=np.random.uniform(-1,1,size=(3,4))
ary

array([[ 0.13321602,  0.06680186, -0.19095528,  0.13553702],
       [ 0.66845354, -0.82790788, -0.57321856, -0.86043159],
       [ 0.61942449, -0.31626971, -0.29771629,  0.34908214]])

In [15]:
sum=ary.cumsum()
sum[sum.argmax()]

0.81305315125061539