In [10]:
import numpy as np
name=np.array(["王静雯","蔺婧","靳文龙","白卓岩","许言"])
subject=np.array(["Math","English","Python","Chinese","Art","Database","Physics"])
name,subject
name.ndim
name.size
name.dtype

dtype('<U3')

In [15]:
name.ndim      #数组维度

1

In [13]:
name.size      #数组元素个数

5

In [16]:
name.dtype     #数组数据类型

dtype('<U3')

In [19]:
name[2],subject[3],subject[-1]

('靳文龙', 'Chinese', 'Physics')

In [20]:
subject[[0,2,4]]   #[0,2,4]：索引列表

array(['Math', 'Python', 'Art'], 
      dtype='<U8')

In [22]:
name[1:4]          #索引1，2，3

array(['蔺婧', '靳文龙', '白卓岩'], 
      dtype='<U3')

In [23]:
subject[:-1:2]     #索引0，2，4

array(['Math', 'Python', 'Art'], 
      dtype='<U8')

In [9]:
import numpy as np
name=np.array(["王静雯","蔺婧","靳文龙","白卓岩","许言"])
name[(name=="王静雯")|(name=="蔺婧") ]

array(['王静雯', '蔺婧'], 
      dtype='<U3')

In [10]:
mask=(name=="王静雯")|(name=="蔺婧")
mask

array([ True,  True, False, False, False], dtype=bool)

In [11]:
name[mask]

array(['王静雯', '蔺婧'], 
      dtype='<U3')

In [13]:
subject=np.array(["Math","English","Python","Chinese","Art","Database","Physics"])
subject[[0,2,4]]

array(['Math', 'Python', 'Art'], 
      dtype='<U8')

In [16]:
scores=np.array([[70,85,77,90,82,84,89],[60,64,80,75,80,92,90],[90,93,77,76,92,85,62],[88,55,60,95,71,56,59],[77,48,59,86,99,48,58]])
scores

array([[70, 85, 77, 90, 82, 84, 89],
       [60, 64, 80, 75, 80, 92, 90],
       [90, 93, 77, 76, 92, 85, 62],
       [88, 55, 60, 95, 71, 56, 59],
       [77, 48, 59, 86, 99, 48, 58]])

In [17]:
scores.ndim         #数组维数

2

In [18]:
scores.size         #数组元素总数=行数*列数

35

In [19]:
scores.shape        #数组的列数与行数

(5, 7)

In [21]:
scores.dtype        #数组元素的类型

dtype('int32')

In [ ]:
arr[row,column]

In [22]:
scores[1,0]

60

In [23]:
scores[[1,0],[2,1]]

array([80, 85])

In [24]:
scores[[1,3]]

array([[60, 64, 80, 75, 80, 92, 90],
       [88, 55, 60, 95, 71, 56, 59]])

In [25]:
scores[:,[1,2]]

array([[85, 77],
       [64, 80],
       [93, 77],
       [55, 60],
       [48, 59]])

In [26]:
scores[[0,3],1:4]

array([[85, 77, 90],
       [55, 60, 95]])

In [27]:
scores[[1,3]][:,[0,1]]

array([[60, 64],
       [88, 55]])

In [32]:
name=np.array(["王静雯","蔺婧","靳文龙","白卓岩","许言"])
scores=np.array([[70,85,77,90,82,84,89],[60,64,80,75,80,92,90],[90,93,77,76,92,85,62],[88,55,60,95,71,56,59],[77,48,59,86,99,48,58]])
scores[(name=="靳文龙")|(name=="许言"),:]

array([[90, 93, 77, 76, 92, 85, 62],
       [77, 48, 59, 86, 99, 48, 58]])

In [4]:
import numpy as np
name=np.array(["王静雯","蔺婧","靳文龙","白卓岩","许言"])
subject=np.array(["Math","English","Python","Chinese","Art","Database","Physics"])
scores=np.array([[70,85,77,90,82,84,89],[60,64,80,75,80,92,90],[90,93,77,76,92,85,62],[88,55,60,95,71,56,59],[77,48,59,86,99,48,58]])
scores[(name=="王静雯")|(name=="蔺婧")][:,(subject=="Python")|(subject=="Art")]

array([[77, 82],
       [80, 80]])

In [9]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(3,11,2)

array([3, 5, 7, 9])

In [11]:
np.arange(0.3,1.5,0.3)

array([ 0.3,  0.6,  0.9,  1.2])

In [12]:
np.arange(0,15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [14]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])